### ISSUE TITLE
( Enhancement | Suggestion ) Maybe using gobuilder.me to build packages for various OS's.

### ISSUE THREAD

**Issue by sebie** [yhat/scrape#1]
I submitted it to [gobuilder.me](https://gobuilder.me) and it finished the build in a few seconds.

The [result](https://gobuilder.me/github.com/yhat/scrape) is packages for nearly every used operating system, ready to go.

---

Suggestions:
- Maybe a webhook, to automatically build it when a new commit occurs
- `.gobuilder.yml` file to customize the build process.

More information on both of them is available [here](https://gobuilder.me/help).

---

I am not affiliated, nor promoting Gobuilder for comercial purposes. :wink: 

Congratulations on getting onto the front page of Hacker News :).

**Comment by ericchiang** [comment]
Don't really see the point of this. Sorry.

**Comment by sebie** [comment]
Fair enough. Have a good day.
